# Generated by Django 4.2.19 on 2025-04-05 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='supplier',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='expiry_date',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='date_added',
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='owner',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
