# Generated by Django 4.2.19 on 2025-04-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_medicine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='last_updated',
        ),
    ]
