# Generated by Django 4.2.19 on 2025-04-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_medicine_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
