# Generated by Django 4.2.19 on 2025-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_medicine_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.IntegerField(max_length=100),
        ),
    ]
